import "./src/assets/styles/globals.css"
import "./src/assets/styles/style.css"
// import "./src/assets/styles/style-rtl.css"
import "./src/assets/styles/print.css"
import "./src/assets/styles/style-wp-head.css"
